//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.notes = new HashSet<note>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<note> notes { get; set; }
    }
}
