//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Исходное имя файла:
// Дата создания: 15.12.2017 22:58:09
namespace client.MSUWS
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для WSEntities.
    /// </summary>
    public partial class WSEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Инициализируйте новый объект WSEntities.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WSEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WSModel", "client.MSUWS");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("client.MSUWS", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WSModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для students.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<student> students
        {
            get
            {
                if ((this._students == null))
                {
                    this._students = base.CreateQuery<student>("students");
                }
                return this._students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<student> _students;
        /// <summary>
        /// В схеме отсутствуют комментарии для notes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<note> notes
        {
            get
            {
                if ((this._notes == null))
                {
                    this._notes = base.CreateQuery<note>("notes");
                }
                return this._notes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<note> _notes;
        /// <summary>
        /// В схеме отсутствуют комментарии для students.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTostudents(student student)
        {
            base.AddObject("students", student);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для notes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTonotes(note note)
        {
            base.AddObject("notes", note);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WSModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Entity" +
                "Type Name=\"student\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"name\" Type=\"Edm.String\" Nullable" +
                "=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty" +
                " Name=\"notes\" Relationship=\"WSModel.FK_notes_students\" ToRole=\"note\" FromRole=\"s" +
                "tudent\" /></EntityType><EntityType Name=\"note\"><Key><PropertyRef Name=\"id\" /><Pr" +
                "opertyRef Name=\"notes\" /><PropertyRef Name=\"subject\" /></Key><Property Name=\"id\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"subject\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"notes\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"studen" +
                "t\" Relationship=\"WSModel.FK_notes_students\" ToRole=\"student\" FromRole=\"note\" /><" +
                "/EntityType><Association Name=\"FK_notes_students\"><End Type=\"WSModel.student\" Ro" +
                "le=\"student\" Multiplicity=\"1\" /><End Type=\"WSModel.note\" Role=\"note\" Multiplicit" +
                "y=\"*\" /><ReferentialConstraint><Principal Role=\"student\"><PropertyRef Name=\"id\" " +
                "/></Principal><Dependent Role=\"note\"><PropertyRef Name=\"id\" /></Dependent></Refe" +
                "rentialConstraint></Association></Schema><Schema Namespace=\"ws_service\" xmlns=\"h" +
                "ttp://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"WSEntities\" " +
                "m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://" +
                "schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"students\" Ent" +
                "ityType=\"WSModel.student\" /><EntitySet Name=\"notes\" EntityType=\"WSModel.note\" />" +
                "<AssociationSet Name=\"FK_notes_students\" Association=\"WSModel.FK_notes_students\"" +
                "><End Role=\"student\" EntitySet=\"students\" /><End Role=\"note\" EntitySet=\"notes\" /" +
                "></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для WSModel.student.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("students")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class student : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект student.
        /// </summary>
        /// <param name="ID">Начальное значение id.</param>
        /// <param name="name">Начальное значение name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static student Createstudent(int ID, string name)
        {
            student student = new student();
            student.id = ID;
            student.name = name;
            return student;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для notes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<note> notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this._notes = value;
                this.OnPropertyChanged("notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<note> _notes = new global::System.Data.Services.Client.DataServiceCollection<note>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для WSModel.note.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// notes
    /// subject
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("notes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id", "notes", "subject")]
    public partial class note : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект note.
        /// </summary>
        /// <param name="ID">Начальное значение id.</param>
        /// <param name="subject">Начальное значение subject.</param>
        /// <param name="notes">Начальное значение notes.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static note Createnote(int ID, string subject, int notes)
        {
            note note = new note();
            note.id = ID;
            note.subject = subject;
            note.notes = notes;
            return note;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства subject.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string subject
        {
            get
            {
                return this._subject;
            }
            set
            {
                this.OnsubjectChanging(value);
                this._subject = value;
                this.OnsubjectChanged();
                this.OnPropertyChanged("subject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _subject;
        partial void OnsubjectChanging(string value);
        partial void OnsubjectChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства notes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this.OnnotesChanging(value);
                this._notes = value;
                this.OnnotesChanged();
                this.OnPropertyChanged("notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _notes;
        partial void OnnotesChanging(int value);
        partial void OnnotesChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для student.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public student student
        {
            get
            {
                return this._student;
            }
            set
            {
                this._student = value;
                this.OnPropertyChanged("student");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private student _student;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
